In [1]:
import numpy as np
import torch
from torch import nn
import matplotlib.pyplot as plt

In [2]:
import torch

torch.manual_seed(42)

weights = torch.tensor([3.0, 2.0, 0.5])
bias = 4.0

X = torch.rand(100, 3)  # 3 features
# Calculate targets
y = X @ weights + bias  # @ = matrix multiplication
y = y.unsqueeze(dim=1)

# Print shapes
print(f"X shape: {X.shape}")  # (100, 3)
print(f"y shape: {y.shape}")  # (100,)

X shape: torch.Size([100, 3])
y shape: torch.Size([100, 1])


In [3]:
X[:10], y[:10]

(tensor([[0.8823, 0.9150, 0.3829],
         [0.9593, 0.3904, 0.6009],
         [0.2566, 0.7936, 0.9408],
         [0.1332, 0.9346, 0.5936],
         [0.8694, 0.5677, 0.7411],
         [0.4294, 0.8854, 0.5739],
         [0.2666, 0.6274, 0.2696],
         [0.4414, 0.2969, 0.8317],
         [0.1053, 0.2695, 0.3588],
         [0.1994, 0.5472, 0.0062]]),
 tensor([[8.6682],
         [7.9593],
         [6.8274],
         [6.5655],
         [8.1142],
         [7.3461],
         [6.1895],
         [6.3338],
         [5.0343],
         [5.6956]]))

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)
len(X_train), len(y_train), len(X_test), len(y_test)

(80, 80, 20, 20)

In [5]:
# Building a Multiple linear regression model
class LinearRegressionModel(nn.Module):
  def __init__(self):
    super().__init__()
    self.weights = nn.Parameter(torch.randn(3, 1,
                                            dtype = torch.float),
                                            requires_grad=True)
    self.bias = nn.Parameter(torch.randn(1,
                                         dtype = torch.float),
                                         requires_grad=True)
    # Forward computation
  def forward(self, x : torch.Tensor) -> torch.Tensor:
    return x @ self.weights + self.bias


In [6]:
torch.manual_seed(42)
model = LinearRegressionModel()
print(X_test.shape)
model.state_dict()

torch.Size([20, 3])


OrderedDict([('weights',
              tensor([[0.3367],
                      [0.1288],
                      [0.2345]])),
             ('bias', tensor([0.2303]))])

In [7]:
list(model.parameters())

[Parameter containing:
 tensor([[0.3367],
         [0.1288],
         [0.2345]], requires_grad=True),
 Parameter containing:
 tensor([0.2303], requires_grad=True)]

In [8]:
with torch.inference_mode():
  y_pred = model(X_test)

In [9]:
loss_fn = nn.MSELoss()
optimizer = torch.optim.SGD(params = model.parameters(), lr = 0.01)

In [10]:
epochs = 1000
epoch_count = []
train_loss_values = []
test_loss_values = []

for epoch in range(epochs):
  model.train()                    # Training mode
  y_pred = model(X_train)          # Forward passs
  loss = loss_fn(y_pred, y_train)  # Calculate the loss function / cost function
  optimizer.zero_grad()            # Optimizer zero grad
  loss.backward()                  # Back propogation
  optimizer.step()                 # Perform gradient descent

  model.eval()                     # Testing mode
  with torch.inference_mode():
    test_pred = model(X_test)
    test_loss = loss_fn(test_pred, y_test)
  if epoch % 20 == 0:
    epoch_count.append(epoch)
    train_loss_values.append(loss.item())
    test_loss_values.append(test_loss.item())
    print(f" Epoch : {epoch} | Loss : {loss} | Test loss : {test_loss}")

 Epoch : 0 | Loss : 36.903995513916016 | Test loss : 37.15770721435547
 Epoch : 20 | Loss : 9.533628463745117 | Test loss : 9.881455421447754
 Epoch : 40 | Loss : 2.576110363006592 | Test loss : 2.807033061981201
 Epoch : 60 | Loss : 0.8005229234695435 | Test loss : 0.9325218200683594
 Epoch : 80 | Loss : 0.3408392369747162 | Test loss : 0.4136367738246918
 Epoch : 100 | Loss : 0.2157241404056549 | Test loss : 0.2566774785518646
 Epoch : 120 | Loss : 0.17605631053447723 | Test loss : 0.20059601962566376
 Epoch : 140 | Loss : 0.15856845676898956 | Test loss : 0.17477834224700928
 Epoch : 160 | Loss : 0.14717131853103638 | Test loss : 0.15914934873580933
 Epoch : 180 | Loss : 0.13775202631950378 | Test loss : 0.14754167199134827
 Epoch : 200 | Loss : 0.12923920154571533 | Test loss : 0.13785050809383392
 Epoch : 220 | Loss : 0.1213357076048851 | Test loss : 0.12926584482192993
 Epoch : 240 | Loss : 0.11394210904836655 | Test loss : 0.12143498659133911
 Epoch : 260 | Loss : 0.107011064887

In [11]:
print("Learned weights:", model.weights.data.view(-1))  # view(-1) to print as flat vector
print("Learned bias:", model.bias.data)

print("True weights: [3.0, 2.0, 0.5]")
print("True bias: 4.0")

Learned weights: tensor([2.7753, 2.0791, 0.7946])
Learned bias: tensor([3.9215])
True weights: [3.0, 2.0, 0.5]
True bias: 4.0


In [19]:
import torch

torch.manual_seed(42)

weights = torch.tensor([3.0, 2.0, 0.5])
bias = 4.0

X = torch.rand(100, 3)  # 3 features
# Calculate targets
y = X @ weights + bias  # @ = matrix multiplication
y = y.unsqueeze(dim=1)

# Print shapes
print(f"X shape: {X.shape}")  # (100, 3)
print(f"y shape: {y.shape}")  # (100,)

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)
len(X_train), len(y_train), len(X_test), len(y_test)

# Building a Multiple linear regression model
class LinearRegressionModel(nn.Module):
  def __init__(self):
    super().__init__()
    self.linear_layer = nn.Linear(in_features = 3,
                                  out_features = 1)
    # Forward computation
  def forward(self, x : torch.Tensor) -> torch.Tensor:
    return self.linear_layer(x)

torch.manual_seed(42)
model = LinearRegressionModel()
print(X_test.shape)
model.state_dict()

with torch.inference_mode():
  y_pred = model(X_test)
y_pred

loss_fn = nn.L1Loss()
optimizer = torch.optim.SGD(params = model.parameters(), lr = 0.5)

epochs = 1000
epoch_count = []
train_loss_values = []
test_loss_values = []

for epoch in range(epochs):
  model.train()                    # Training mode
  y_pred = model(X_train)          # Forward passs
  loss = loss_fn(y_pred, y_train)  # Calculate the loss function / cost function
  optimizer.zero_grad()            # Optimizer zero grad
  loss.backward()                  # Back propogation
  optimizer.step()                 # Perform gradient descent

  model.eval()                     # Testing mode
  with torch.inference_mode():
    test_pred = model(X_test)
    test_loss = loss_fn(test_pred, y_test)
  if epoch % 20 == 0:
    epoch_count.append(epoch)
    train_loss_values.append(loss.item())
    test_loss_values.append(test_loss.item())
    print(f" Epoch : {epoch} | Loss : {loss} | Test loss : {test_loss}")

X shape: torch.Size([100, 3])
y shape: torch.Size([100, 1])
torch.Size([20, 3])
 Epoch : 0 | Loss : 5.647582054138184 | Test loss : 5.0362548828125
 Epoch : 20 | Loss : 0.34112492203712463 | Test loss : 0.40022268891334534
 Epoch : 40 | Loss : 0.3111884295940399 | Test loss : 0.46072110533714294
 Epoch : 60 | Loss : 0.3111884295940399 | Test loss : 0.46072110533714294
 Epoch : 80 | Loss : 0.3111884295940399 | Test loss : 0.46072110533714294
 Epoch : 100 | Loss : 0.3111884295940399 | Test loss : 0.46072110533714294
 Epoch : 120 | Loss : 0.3111884295940399 | Test loss : 0.46072110533714294
 Epoch : 140 | Loss : 0.3111884295940399 | Test loss : 0.46072110533714294
 Epoch : 160 | Loss : 0.3111884295940399 | Test loss : 0.46072110533714294
 Epoch : 180 | Loss : 0.3111884295940399 | Test loss : 0.46072110533714294
 Epoch : 200 | Loss : 0.3111884295940399 | Test loss : 0.46072110533714294
 Epoch : 220 | Loss : 0.3111884295940399 | Test loss : 0.46072110533714294
 Epoch : 240 | Loss : 0.311188

In [17]:
from pathlib import Path

MODEL_PATH = Path("Models")
MODEL_PATH.mkdir(parents = True, exist_ok = True)

MODEL_NAME = "Multiple_linear_resgreesion.pth"
MODEL_SAVE_PATH = MODEL_PATH / MODEL_NAME

print(f" Saving model to : {MODEL_SAVE_PATH}")
torch.save(obj=model.state_dict(), f = MODEL_SAVE_PATH)

 Saving model to : Models/Multiple_linear_resgreesion.pth
